# Generated by Django 3.2.25 on 2024-10-12 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_plan_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
