# Generated by Django 3.2.25 on 2024-11-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shoppreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=255, unique=True)),
                ('show_google_privacy_policy', models.BooleanField(default=False)),
                ('show_privacy_policy_link', models.BooleanField(default=False)),
                ('use_specific_privacy_policy', models.BooleanField(default=False)),
                ('selected_option', models.CharField(default='Shopify Policy (/policies/privacy-policy)', max_length=100)),
            ],
        ),
    ]
