# Generated by Django 3.2.25 on 2024-10-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='shop_url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
