# Generated by Django 3.2.25 on 2024-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_store_selected_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='selected_theme',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
