# Generated by Django 3.2.25 on 2024-09-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=255, unique=True)),
                ('banner_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
