# Generated by Django 3.2.25 on 2024-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_privacypolicysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
