# Generated by Django 3.2.25 on 2024-11-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cookiepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiepreference',
            name='shop_url',
            field=models.CharField(default='default_shop_url', max_length=255, unique=True),
        ),
    ]
