# Generated by Django 3.2.25 on 2024-10-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_store_selected_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='selected_theme',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
