# Generated by Django 3.2.25 on 2024-11-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cookiepreference_shop_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiepreference',
            name='shop_url',
            field=models.CharField(default='default_shop_url', max_length=255),
        ),
    ]
