# Generated by Django 3.2.25 on 2024-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cookiepreference_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiepreference',
            name='selected_preferences',
            field=models.JSONField(null=True),
        ),
    ]
